# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3])


# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([ [1,2,3]  ])


# Create a 3-dimensional Numpy array using np.array()
arr3= np.array([
    [
    [ 1,2,3 ] , [4,5,6]
    ] 
])
arr1.ndim , arr2.ndim ,arr3.ndim



(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

arr1.shape , arr1.ndim , arr1.dtype , arr1.size , type(arr1)


((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array

arr2.shape , arr2.ndim , arr2.dtype , arr2.size , type(arr2)


((1, 3), 2, dtype('int32'), 3, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
arr3.shape , arr3.ndim , arr3.dtype , arr3.size , type(arr3)


((1, 2, 3), 3, dtype('int32'), 6, numpy.ndarray)

In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arr2_df = pd.DataFrame(arr2)
arr2_df

0  1  2
0  1  2  3

In [17]:
# Create an array of shape (10, 2) with only ones

ones = np.ones(shape=(10,2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros

zeros = np.zeros(shape = (7,2,3))

zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,101,3)


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint( 0 , 11 , size= (7,2))


array([[ 9,  4],
       [ 0,  6],
       [ 3,  2],
       [ 1,  0],
       [ 6,  6],
       [ 5,  8],
       [10,  8]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

np.random.random_sample( size = (3,5)
                       )


array([[0.03469399, 0.25143829, 0.84445332, 0.96001691, 0.40357517],
       [0.56751142, 0.11983554, 0.51175575, 0.68100583, 0.34430978],
       [0.45621226, 0.3642484 , 0.17331884, 0.77774797, 0.86393738]])

In [22]:



# Create a random array of numbers between 0 & 10 of size (4, 6)

np.random.randint( 0 , 11 , size = (4,6))


array([[10,  0,  9,  6,  9,  4],
       [ 8,  5,  8,  4,  0,  3],
       [ 9,  2,  5,  6,  3,  3],
       [ 4,  7, 10,  4, 10,  3]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [26]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

ranarr= np.random.randint( 1,10,size = (3,7))



# Find the unique numbers in the array you just created
ranarr,np.unique(ranarr)


(array([[6, 2, 4, 9, 7, 9, 6],
        [2, 4, 6, 5, 1, 7, 2],
        [6, 2, 6, 7, 1, 5, 9]]),
 array([1, 2, 4, 5, 6, 7, 9]))

In [27]:
# Find the 0'th index of the latest array you created

ranarr[0]


array([6, 2, 4, 9, 7, 9, 6])

In [29]:
# Get the first 2 rows of latest array you created

ranarr[0:2]


array([[6, 2, 4, 9, 7, 9, 6],
       [2, 4, 6, 5, 1, 7, 2]])

In [43]:
# Get the first 2 values of the first 2 rows of the latest array

tworows = ranarr[0:2]

tworows[0][0:2],tworows[1][0:2]


(array([6, 2]), array([2, 4]))

In [45]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

newwran = np.random.randint(0,10,size = (3,5))

newwones = np.ones( shape=(3,5))

newwones,newwran


(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[5, 7, 1, 8, 3],
        [0, 2, 3, 9, 6],
        [0, 6, 8, 3, 8]]))

In [46]:
# Add the two arrays together

newwones + newwran


array([[ 6.,  8.,  2.,  9.,  4.],
       [ 1.,  3.,  4., 10.,  7.],
       [ 1.,  7.,  9.,  4.,  9.]])

In [47]:
# Create another array of ones of shape (5, 3)

anones = np.ones(shape=(5,3))


In [49]:
# Try add the array of ones and the other most recent array together

newwones + anones.T


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [50]:
# Create another array of ones of shape (3, 5)

anones2 = np.ones(shape=(3,5))


In [52]:
# Subtract the new array of ones from the other most recent array

anones2 - anones.T


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
# Multiply the ones array with the latest array

anones2 * anones.T


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# Take the latest array to the power of 2 using '**'
anones2 ** 2


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# Do the same thing with np.square()
np.square(anones2)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
# Find the mean of the latest array using np.mean()

np.mean(anones2)


1.0

In [58]:
# Find the maximum of the latest array using np.max()

np.max(arr1)

3

In [59]:
# Find the minimum of the latest array using np.min()

np.min(arr3)


1

In [60]:
# Find the standard deviation of the latest array

np.std( anones2)


0.0

In [61]:
# Find the variance of the latest array

np.var( arr3)

2.9166666666666665

In [63]:
# Reshape the latest array to (3, 5, 1)

reshapedanone2 = anones2.reshape(3,5,1)


In [64]:
# Transpose the latest array
reshapedanone2.T


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

What does the transpose do?

In [68]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

dot1 = np.random.randint(0,10 , size = (3,3))
dot2 = np.random.randint(0,10 , size = (3,2))

dot1 , dot2




(array([[5, 2, 0],
        [9, 3, 0],
        [6, 6, 0]]),
 array([[0, 0],
        [7, 6],
        [7, 8]]))

In [69]:
# Perform a dot product on the two newest arrays you created

np.dot(dot1 , dot2)


array([[14, 12],
       [21, 18],
       [42, 36]])

In [70]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

dot3 = np.random.randint( 0 ,10 , size = (4,3))
dot4 = np.random.randint( 0 ,10 , size = (4,3))



In [71]:
# Perform a dot product on the two newest arrays you created

np.dot(dot3 , dot4)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [72]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(dot3 , dot4.T)

array([[ 98,  31, 113,  53],
       [ 78,  33, 119,  61],
       [ 76,  30, 110,  55],
       [130,  40, 165,  73]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [75]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
p1=np.random.randint( 0 ,10 , size = ( 4,3))
p2=np.random.randint( 0 ,10 , size = ( 4,3))
p1,p2


(array([[1, 1, 7],
        [0, 3, 3],
        [6, 2, 9],
        [0, 5, 2]]),
 array([[8, 2, 6],
        [5, 5, 2],
        [2, 7, 0],
        [5, 9, 6]]))

In [76]:

# Compare the two arrays with '>'

p1>p2


array([[False, False,  True],
       [False, False,  True],
       [ True, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [77]:
# Compare the two arrays with '>='

p1>=p2


array([[False, False,  True],
       [False, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [79]:
# Find which elements of the first array are greater than 7

p1 > 7, p2>7


(array([[False, False, False],
        [False, False, False],
        [False, False,  True],
        [False, False, False]]),
 array([[ True, False, False],
        [False, False, False],
        [False, False, False],
        [False,  True, False]]))

In [80]:
# Which parts of each array are equal? (try using '==')

p1 == p2


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [88]:
# Sort one of the arrays you just created in ascending order

sortedp1 =np.sort(p1)

sortedp1



array([[1, 1, 7],
       [0, 3, 3],
       [2, 6, 9],
       [0, 2, 5]])

In [89]:
# Sort the indexes of one of the arrays you just created

np.argsort(p1)



array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [91]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(p1)


8

In [92]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(p1)


3

In [93]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(p1 , axis=1)


array([2, 1, 2, 2], dtype=int64)

In [94]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(p1 , axis=0)


array([1, 0, 1], dtype=int64)

In [108]:
# Create an array of normally distributed random numbers

en=np.random.randint( 1 , 15 , size=(1 , 5))
en


array([[13, 14,  4,  2,  4]])

In [112]:
# Create an array with 10 evenly spaced numbers between 1 and 100
en2=np.arange(0,101,10)
en2


array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.